version: "3"
services:
  app:
    build: .
    #image: vtacquet/phpliteadmin:v1.03
    volumes: 
      - ./db:/db:rw
      #- ./html:/var/www/html:rw
      #- ./scripts/:/config/:rw
      #- ./data/users.json.blank:/config/www/private/users.json.blank
    ports:
      - "9081:80"
    environment:
       PASSWORD: password
    #    FB_PASSWORD: password